directories:
  output: release
  buildResources: build
appId: com.yourcompany.leaderprompt
productName: LeaderPrompt
files:
  - filter:
      - dist/**/*
      - electron/**/*
win:
  target: nsis
electronVersion: 37.1.0
